spring.application.name=incidentTracker

# 1. Database Connection URL
# Syntax: jdbc:postgresql://<host>:<port>/<database_name>
spring.datasource.url=jdbc:postgresql://localhost:5432/incident_db

# 2. Database Credentials
spring.datasource.username=postgres
spring.datasource.password=root

# 3. Driver Class
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. JPA / Hibernate Settings
# 'validate' is safest since we created the schema.sql manually
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 5. Enable SQL Script Initialization (for your schema.sql)
spring.sql.init.mode=always

spring.sql.init.separator=^^